In [2]:
import numpy as np

#Next word prediction numerical example

In [3]:
c = [1, 0, 0, 0]
a = [0, 1, 0, 0]
t = [0, 0, 1, 0]
s = [0, 0, 0, 1]

Lets assume that the prediction for `c` has already been done. Now lets do the prediction for `a`

#Forget gate

In [4]:
w_f = np.array([
    [.1, -.2,.7 ,.8,.7,.9, .1],
    [.2,-.5,.1,.6,.8,-.9,.3],
    [.6,.1,.3,-.4,-.3,-.1,-.56]


])

In [5]:
w_f

array([[ 0.1 , -0.2 ,  0.7 ,  0.8 ,  0.7 ,  0.9 ,  0.1 ],
       [ 0.2 , -0.5 ,  0.1 ,  0.6 ,  0.8 , -0.9 ,  0.3 ],
       [ 0.6 ,  0.1 ,  0.3 , -0.4 , -0.3 , -0.1 , -0.56]])

In [6]:
h_x  = np.array([[
    .1,
    .2,
    .7,
    0,
    1,
    0,
    0
]]).T

In [7]:
h_x

array([[0.1],
       [0.2],
       [0.7],
       [0. ],
       [1. ],
       [0. ],
       [0. ]])

In [8]:
b_f = np.array([
       [-0.3],
       [0.2],
       [0.4],
                ])
b_f

array([[-0.3],
       [ 0.2],
       [ 0.4]])

In [9]:
def sigmoid(x):
  result = (1/(1+np.exp(-x)))
  result[result > 0.5] = 1
  result[result<=0.5] =0
  return result

In [10]:
f_t =  sigmoid(  np.dot(w_f, h_x) + b_f  )
f_t

array([[1.],
       [1.],
       [1.]])

# Candidate cell

In [11]:
w_c = w_f = np.array([
    [.41, .32,-.7 ,.8,.7,.9, .1],
    [.22,-.25,.41,.6,-.18,-.39,-.13],
    [-.16,.31,-.13,-.54,-.73,.51,-.56]


])

In [12]:
b_c = np.array([
       [-0.9],
       [-0.7],
       [0.4],
                ])
b_c

array([[-0.9],
       [-0.7],
       [ 0.4]])

In [13]:
c_tilda = np.tanh(  np.dot( w_c , h_x ) + b_c  )

c_tilda

array([[-0.52629003],
       [-0.5518239 ],
       [-0.3583574 ]])

In [14]:
np.dot(w_f, h_x) + b_f

array([[ 0.015],
       [ 0.279],
       [-0.375]])

#Input gate

In [15]:
w_i = np.array([
    [-.41, .32,-.27 ,.98,.17,.39, .51],
    [.22,-.25,.541,.66,-.318,-.329,-.13],
    [-.916,.831,-.613,-.54,-.273,.51,-.56]


])
b_i = np.array([
       [-0.9],
       [0.7],
       [0.4],
                ])

In [16]:
i_t = sigmoid(  np.dot(w_i, h_x) + b_i  )
i_t

array([[0.],
       [1.],
       [0.]])

In [17]:
c_t_old = np.array([
       [.1],
       [.9],
       [.5]])

#C_t update

In [18]:
c_t = (f_t*c_t_old) + (i_t * c_tilda)

In [19]:
c_t

array([[0.1      ],
       [0.3481761],
       [0.5      ]])

# Output gate

In [20]:
w_o = np.array([
    [-.1, .32,.27 ,.8,.17,.39, .51],
    [.22,-.25,.541,.66,-.38,-.39,.13],
    [-.96,.831,.613,-.94,-.73,.51,-.56]


])
b_o = np.array([
       [-0.3],
       [0.4],
       [0.1],
                ])

In [21]:
o_t = sigmoid(  np.dot(w_o, h_x) + b_o  )
o_t


array([[1.],
       [1.],
       [0.]])

#h_t update

In [22]:
h_t = o_t* np.tanh(c_t)
h_t

array([[0.09966799],
       [0.33475702],
       [0.        ]])

#Predicting next word

In [23]:
w_y = np.array([
    [0.2, -.9,-.8],
    [-.1, .2, .3],
    [.3,.4,.7],
    [-.3,.4,.7]

])
w_y

array([[ 0.2, -0.9, -0.8],
       [-0.1,  0.2,  0.3],
       [ 0.3,  0.4,  0.7],
       [-0.3,  0.4,  0.7]])

In [24]:
b_y = np.array([[1.],
       [1.],
       [0.],
        [.5]])

In [25]:
def softmax(x):
  result = []
  for i in x:
    result.append(np.exp(i)/np.sum(np.exp(x))   )
  return(np.array(result))


In [26]:
y = softmax(np.dot(w_y, h_t) + b_y)
y

array([[0.25850188],
       [0.36257644],
       [0.14842116],
       [0.23050052]])